name: Automated test

# when is running
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: ${{ matrix.version }}
        id: setup-chrome
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
      - if: runner.os == 'Windows'
        run: |
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest


