name: Install Selenoid and Run UI Tests CI

on:
  push:
  pull_request:

jobs:
  install-selenoid-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Install Selenoid
      run: |
        sudo curl -sSLO https://github.com/aerokube/cm/releases/download/1.9.1/cm_linux_amd64
        sudo mv cm_linux_amd64 /usr/local/bin/cm
        sudo chmod +x /usr/local/bin/cm
        sudo cm version

    - name: Start Selenoid
      run: sudo cm selenoid start --vnc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest --driver Remote --capability browserName chrome
