name: Install Chrome and Run Tests CI

on:
  push:
  pull_request:

jobs:
  install-chrome-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Selenium
      run: |
        pip install selenium

    - name: Download and run Selenium Standalone Server (Selenoid)
      run: |
        wget -O selenoid https://github.com/aerokube/selenoid/releases/download/v1.10.3/selenoid_linux_amd64
        chmod +x selenoid
        ./selenoid start --vnc

    - name: Run Tests
      run: |
        python web_tests

